// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: messages.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Peariscope_StreamChannel: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case video // = 0
  case input // = 1
  case control // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .video
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .video
    case 1: self = .input
    case 2: self = .control
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .video: return 0
    case .input: return 1
    case .control: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Peariscope_StreamChannel] = [
    .video,
    .input,
    .control,
  ]

}

public enum Peariscope_Codec: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case h264 // = 0
  case h265 // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .h264
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .h264
    case 1: self = .h265
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .h264: return 0
    case .h265: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Peariscope_Codec] = [
    .h264,
    .h265,
  ]

}

/// Top-level message wrapper for IPC between native layer and Pear runtime
public struct Peariscope_IpcMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Request/response correlation ID
  public var id: UInt32 = 0

  public var payload: Peariscope_IpcMessage.OneOf_Payload? = nil

  /// Networking commands (native -> pear)
  public var startHosting: Peariscope_StartHosting {
    get {
      if case .startHosting(let v)? = payload {return v}
      return Peariscope_StartHosting()
    }
    set {payload = .startHosting(newValue)}
  }

  public var stopHosting: Peariscope_StopHosting {
    get {
      if case .stopHosting(let v)? = payload {return v}
      return Peariscope_StopHosting()
    }
    set {payload = .stopHosting(newValue)}
  }

  public var connectToPeer: Peariscope_ConnectToPeer {
    get {
      if case .connectToPeer(let v)? = payload {return v}
      return Peariscope_ConnectToPeer()
    }
    set {payload = .connectToPeer(newValue)}
  }

  public var disconnect: Peariscope_Disconnect {
    get {
      if case .disconnect(let v)? = payload {return v}
      return Peariscope_Disconnect()
    }
    set {payload = .disconnect(newValue)}
  }

  /// Networking events (pear -> native)
  public var peerConnected: Peariscope_PeerConnected {
    get {
      if case .peerConnected(let v)? = payload {return v}
      return Peariscope_PeerConnected()
    }
    set {payload = .peerConnected(newValue)}
  }

  public var peerDisconnected: Peariscope_PeerDisconnected {
    get {
      if case .peerDisconnected(let v)? = payload {return v}
      return Peariscope_PeerDisconnected()
    }
    set {payload = .peerDisconnected(newValue)}
  }

  public var hostingStarted: Peariscope_HostingStarted {
    get {
      if case .hostingStarted(let v)? = payload {return v}
      return Peariscope_HostingStarted()
    }
    set {payload = .hostingStarted(newValue)}
  }

  public var hostingStopped: Peariscope_HostingStopped {
    get {
      if case .hostingStopped(let v)? = payload {return v}
      return Peariscope_HostingStopped()
    }
    set {payload = .hostingStopped(newValue)}
  }

  public var connectionEstablished: Peariscope_ConnectionEstablished {
    get {
      if case .connectionEstablished(let v)? = payload {return v}
      return Peariscope_ConnectionEstablished()
    }
    set {payload = .connectionEstablished(newValue)}
  }

  public var connectionFailed: Peariscope_ConnectionFailed {
    get {
      if case .connectionFailed(let v)? = payload {return v}
      return Peariscope_ConnectionFailed()
    }
    set {payload = .connectionFailed(newValue)}
  }

  public var error: Peariscope_Error {
    get {
      if case .error(let v)? = payload {return v}
      return Peariscope_Error()
    }
    set {payload = .error(newValue)}
  }

  /// Data streaming (bidirectional)
  public var streamData: Peariscope_StreamData {
    get {
      if case .streamData(let v)? = payload {return v}
      return Peariscope_StreamData()
    }
    set {payload = .streamData(newValue)}
  }

  /// Status
  public var statusRequest: Peariscope_StatusRequest {
    get {
      if case .statusRequest(let v)? = payload {return v}
      return Peariscope_StatusRequest()
    }
    set {payload = .statusRequest(newValue)}
  }

  public var statusResponse: Peariscope_StatusResponse {
    get {
      if case .statusResponse(let v)? = payload {return v}
      return Peariscope_StatusResponse()
    }
    set {payload = .statusResponse(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    /// Networking commands (native -> pear)
    case startHosting(Peariscope_StartHosting)
    case stopHosting(Peariscope_StopHosting)
    case connectToPeer(Peariscope_ConnectToPeer)
    case disconnect(Peariscope_Disconnect)
    /// Networking events (pear -> native)
    case peerConnected(Peariscope_PeerConnected)
    case peerDisconnected(Peariscope_PeerDisconnected)
    case hostingStarted(Peariscope_HostingStarted)
    case hostingStopped(Peariscope_HostingStopped)
    case connectionEstablished(Peariscope_ConnectionEstablished)
    case connectionFailed(Peariscope_ConnectionFailed)
    case error(Peariscope_Error)
    /// Data streaming (bidirectional)
    case streamData(Peariscope_StreamData)
    /// Status
    case statusRequest(Peariscope_StatusRequest)
    case statusResponse(Peariscope_StatusResponse)

  }

  public init() {}
}

public struct Peariscope_StartHosting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Host's public key to advertise
  public var publicKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_StopHosting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ConnectToPeer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Short code or full public key hex
  public var connectionCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_Disconnect: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Which peer to disconnect from
  public var peerKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_PeerConnected: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var peerKey: Data = Data()

  public var peerName: String = String()

  /// ID for this peer's streams
  public var streamID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_PeerDisconnected: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var peerKey: Data = Data()

  public var reason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_HostingStarted: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var publicKey: Data = Data()

  /// Short shareable code
  public var connectionCode: String = String()

  /// Local IP for direct TCP relay (iOS)
  public var relayHost: String = String()

  /// TCP port for relay
  public var relayPort: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_HostingStopped: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ConnectionEstablished: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var peerKey: Data = Data()

  public var streamID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ConnectionFailed: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var connectionCode: String = String()

  public var reason: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_Error: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: UInt32 = 0

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_StreamData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: UInt32 = 0

  public var channel: Peariscope_StreamChannel = .video

  public var data: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_InputEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timestampMs: UInt32 = 0

  public var event: Peariscope_InputEvent.OneOf_Event? = nil

  public var key: Peariscope_KeyEvent {
    get {
      if case .key(let v)? = event {return v}
      return Peariscope_KeyEvent()
    }
    set {event = .key(newValue)}
  }

  public var mouseMove: Peariscope_MouseMoveEvent {
    get {
      if case .mouseMove(let v)? = event {return v}
      return Peariscope_MouseMoveEvent()
    }
    set {event = .mouseMove(newValue)}
  }

  public var mouseButton: Peariscope_MouseButtonEvent {
    get {
      if case .mouseButton(let v)? = event {return v}
      return Peariscope_MouseButtonEvent()
    }
    set {event = .mouseButton(newValue)}
  }

  public var scroll: Peariscope_ScrollEvent {
    get {
      if case .scroll(let v)? = event {return v}
      return Peariscope_ScrollEvent()
    }
    set {event = .scroll(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Event: Equatable, Sendable {
    case key(Peariscope_KeyEvent)
    case mouseMove(Peariscope_MouseMoveEvent)
    case mouseButton(Peariscope_MouseButtonEvent)
    case scroll(Peariscope_ScrollEvent)

  }

  public init() {}
}

public struct Peariscope_KeyEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Platform-neutral keycode
  public var keycode: UInt32 = 0

  /// Bitmask: shift=1, ctrl=2, alt=4, meta=8
  public var modifiers: UInt32 = 0

  /// true = down, false = up
  public var pressed: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_MouseMoveEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Normalized 0.0-1.0 relative to screen
  public var x: Float = 0

  public var y: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_MouseButtonEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0=left, 1=right, 2=middle
  public var button: UInt32 = 0

  public var pressed: Bool = false

  public var x: Float = 0

  public var y: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ScrollEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deltaX: Float = 0

  public var deltaY: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ControlMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var msg: Peariscope_ControlMessage.OneOf_Msg? = nil

  public var codecNegotiation: Peariscope_CodecNegotiation {
    get {
      if case .codecNegotiation(let v)? = msg {return v}
      return Peariscope_CodecNegotiation()
    }
    set {msg = .codecNegotiation(newValue)}
  }

  public var requestIdr: Peariscope_RequestIdr {
    get {
      if case .requestIdr(let v)? = msg {return v}
      return Peariscope_RequestIdr()
    }
    set {msg = .requestIdr(newValue)}
  }

  public var qualityReport: Peariscope_QualityReport {
    get {
      if case .qualityReport(let v)? = msg {return v}
      return Peariscope_QualityReport()
    }
    set {msg = .qualityReport(newValue)}
  }

  public var clipboard: Peariscope_ClipboardData {
    get {
      if case .clipboard(let v)? = msg {return v}
      return Peariscope_ClipboardData()
    }
    set {msg = .clipboard(newValue)}
  }

  public var frameTimestamp: Peariscope_FrameTimestamp {
    get {
      if case .frameTimestamp(let v)? = msg {return v}
      return Peariscope_FrameTimestamp()
    }
    set {msg = .frameTimestamp(newValue)}
  }

  public var peerChallenge: Peariscope_PeerChallenge {
    get {
      if case .peerChallenge(let v)? = msg {return v}
      return Peariscope_PeerChallenge()
    }
    set {msg = .peerChallenge(newValue)}
  }

  public var peerChallengeResponse: Peariscope_PeerChallengeResponse {
    get {
      if case .peerChallengeResponse(let v)? = msg {return v}
      return Peariscope_PeerChallengeResponse()
    }
    set {msg = .peerChallengeResponse(newValue)}
  }

  public var displayList: Peariscope_DisplayList {
    get {
      if case .displayList(let v)? = msg {return v}
      return Peariscope_DisplayList()
    }
    set {msg = .displayList(newValue)}
  }

  public var switchDisplay: Peariscope_SwitchDisplay {
    get {
      if case .switchDisplay(let v)? = msg {return v}
      return Peariscope_SwitchDisplay()
    }
    set {msg = .switchDisplay(newValue)}
  }

  public var cursorPosition: Peariscope_CursorPosition {
    get {
      if case .cursorPosition(let v)? = msg {return v}
      return Peariscope_CursorPosition()
    }
    set {msg = .cursorPosition(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Msg: Equatable, Sendable {
    case codecNegotiation(Peariscope_CodecNegotiation)
    case requestIdr(Peariscope_RequestIdr)
    case qualityReport(Peariscope_QualityReport)
    case clipboard(Peariscope_ClipboardData)
    case frameTimestamp(Peariscope_FrameTimestamp)
    case peerChallenge(Peariscope_PeerChallenge)
    case peerChallengeResponse(Peariscope_PeerChallengeResponse)
    case displayList(Peariscope_DisplayList)
    case switchDisplay(Peariscope_SwitchDisplay)
    case cursorPosition(Peariscope_CursorPosition)

  }

  public init() {}
}

/// Sent by host at high frequency for client-side cursor rendering.
/// Viewer renders a local cursor sprite at this position for low-latency feel.
public struct Peariscope_CursorPosition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Normalized 0.0-1.0 relative to screen
  public var x: Float = 0

  public var y: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sent by host to new peer — contains a 4-digit PIN for out-of-band verification
public struct Peariscope_PeerChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pin: String = String()

  public var peerKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sent by viewer to confirm the PIN displayed on the host
public struct Peariscope_PeerChallengeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var pin: String = String()

  public var accepted: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sent by host to advertise available displays
public struct Peariscope_DisplayList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displays: [Peariscope_DisplayInfo] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_DisplayInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayID: UInt32 = 0

  public var width: UInt32 = 0

  public var height: UInt32 = 0

  public var name: String = String()

  public var isActive: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sent by viewer to request switching to a different display
public struct Peariscope_SwitchDisplay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Sent alongside video frames for latency measurement.
/// Host embeds capture time, viewer measures delta to calculate end-to-end latency.
public struct Peariscope_FrameTimestamp: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// milliseconds since epoch
  public var captureTimeMs: UInt64 = 0

  /// monotonic frame counter
  public var frameID: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_CodecNegotiation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportedCodecs: [Peariscope_Codec] = []

  public var selectedCodec: Peariscope_Codec = .h264

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_RequestIdr: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_QualityReport: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rttMs: UInt32 = 0

  /// 0.0-1.0
  public var packetLoss: Float = 0

  public var bitrateKbps: UInt32 = 0

  public var fps: UInt32 = 0

  /// Viewer's native screen width in pixels
  public var screenWidth: UInt32 = 0

  /// Viewer's native screen height in pixels
  public var screenHeight: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_ClipboardData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var text: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_StatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_StatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isHosting: Bool = false

  public var isConnected: Bool = false

  public var connectedPeers: [Peariscope_PeerInfo] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Peariscope_PeerInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var publicKey: Data = Data()

  public var name: String = String()

  public var rttMs: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "peariscope"

extension Peariscope_StreamChannel: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STREAM_CHANNEL_VIDEO\0\u{1}STREAM_CHANNEL_INPUT\0\u{1}STREAM_CHANNEL_CONTROL\0")
}

extension Peariscope_Codec: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CODEC_H264\0\u{1}CODEC_H265\0")
}

extension Peariscope_IpcMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IpcMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{4}\u{9}start_hosting\0\u{3}stop_hosting\0\u{3}connect_to_peer\0\u{1}disconnect\0\u{4}\u{7}peer_connected\0\u{3}peer_disconnected\0\u{3}hosting_started\0\u{3}hosting_stopped\0\u{3}connection_established\0\u{3}connection_failed\0\u{1}error\0\u{4}\u{4}stream_data\0\u{4}\u{a}status_request\0\u{3}status_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 10: try {
        var v: Peariscope_StartHosting?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .startHosting(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .startHosting(v)
        }
      }()
      case 11: try {
        var v: Peariscope_StopHosting?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .stopHosting(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .stopHosting(v)
        }
      }()
      case 12: try {
        var v: Peariscope_ConnectToPeer?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .connectToPeer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .connectToPeer(v)
        }
      }()
      case 13: try {
        var v: Peariscope_Disconnect?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .disconnect(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .disconnect(v)
        }
      }()
      case 20: try {
        var v: Peariscope_PeerConnected?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .peerConnected(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .peerConnected(v)
        }
      }()
      case 21: try {
        var v: Peariscope_PeerDisconnected?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .peerDisconnected(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .peerDisconnected(v)
        }
      }()
      case 22: try {
        var v: Peariscope_HostingStarted?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .hostingStarted(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .hostingStarted(v)
        }
      }()
      case 23: try {
        var v: Peariscope_HostingStopped?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .hostingStopped(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .hostingStopped(v)
        }
      }()
      case 24: try {
        var v: Peariscope_ConnectionEstablished?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .connectionEstablished(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .connectionEstablished(v)
        }
      }()
      case 25: try {
        var v: Peariscope_ConnectionFailed?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .connectionFailed(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .connectionFailed(v)
        }
      }()
      case 26: try {
        var v: Peariscope_Error?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .error(v)
        }
      }()
      case 30: try {
        var v: Peariscope_StreamData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .streamData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .streamData(v)
        }
      }()
      case 40: try {
        var v: Peariscope_StatusRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .statusRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .statusRequest(v)
        }
      }()
      case 41: try {
        var v: Peariscope_StatusResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .statusResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .statusResponse(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    switch self.payload {
    case .startHosting?: try {
      guard case .startHosting(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .stopHosting?: try {
      guard case .stopHosting(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .connectToPeer?: try {
      guard case .connectToPeer(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .disconnect?: try {
      guard case .disconnect(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case .peerConnected?: try {
      guard case .peerConnected(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .peerDisconnected?: try {
      guard case .peerDisconnected(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case .hostingStarted?: try {
      guard case .hostingStarted(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
    }()
    case .hostingStopped?: try {
      guard case .hostingStopped(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
    }()
    case .connectionEstablished?: try {
      guard case .connectionEstablished(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
    }()
    case .connectionFailed?: try {
      guard case .connectionFailed(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 25)
    }()
    case .error?: try {
      guard case .error(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 26)
    }()
    case .streamData?: try {
      guard case .streamData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
    }()
    case .statusRequest?: try {
      guard case .statusRequest(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
    }()
    case .statusResponse?: try {
      guard case .statusResponse(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 41)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_IpcMessage, rhs: Peariscope_IpcMessage) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_StartHosting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartHosting"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.publicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_StartHosting, rhs: Peariscope_StartHosting) -> Bool {
    if lhs.publicKey != rhs.publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_StopHosting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StopHosting"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_StopHosting, rhs: Peariscope_StopHosting) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ConnectToPeer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectToPeer"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}connection_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.connectionCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.connectionCode.isEmpty {
      try visitor.visitSingularStringField(value: self.connectionCode, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ConnectToPeer, rhs: Peariscope_ConnectToPeer) -> Bool {
    if lhs.connectionCode != rhs.connectionCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_Disconnect: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Disconnect"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}peer_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.peerKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.peerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerKey, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_Disconnect, rhs: Peariscope_Disconnect) -> Bool {
    if lhs.peerKey != rhs.peerKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_PeerConnected: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PeerConnected"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}peer_key\0\u{3}peer_name\0\u{3}stream_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.peerKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.peerName) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.peerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerKey, fieldNumber: 1)
    }
    if !self.peerName.isEmpty {
      try visitor.visitSingularStringField(value: self.peerName, fieldNumber: 2)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_PeerConnected, rhs: Peariscope_PeerConnected) -> Bool {
    if lhs.peerKey != rhs.peerKey {return false}
    if lhs.peerName != rhs.peerName {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_PeerDisconnected: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PeerDisconnected"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}peer_key\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.peerKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.peerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerKey, fieldNumber: 1)
    }
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_PeerDisconnected, rhs: Peariscope_PeerDisconnected) -> Bool {
    if lhs.peerKey != rhs.peerKey {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_HostingStarted: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostingStarted"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_key\0\u{3}connection_code\0\u{3}relay_host\0\u{3}relay_port\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.connectionCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.relayHost) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.relayPort) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.publicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 1)
    }
    if !self.connectionCode.isEmpty {
      try visitor.visitSingularStringField(value: self.connectionCode, fieldNumber: 2)
    }
    if !self.relayHost.isEmpty {
      try visitor.visitSingularStringField(value: self.relayHost, fieldNumber: 3)
    }
    if self.relayPort != 0 {
      try visitor.visitSingularUInt32Field(value: self.relayPort, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_HostingStarted, rhs: Peariscope_HostingStarted) -> Bool {
    if lhs.publicKey != rhs.publicKey {return false}
    if lhs.connectionCode != rhs.connectionCode {return false}
    if lhs.relayHost != rhs.relayHost {return false}
    if lhs.relayPort != rhs.relayPort {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_HostingStopped: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HostingStopped"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_HostingStopped, rhs: Peariscope_HostingStopped) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ConnectionEstablished: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectionEstablished"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}peer_key\0\u{3}stream_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.peerKey) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.peerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerKey, fieldNumber: 1)
    }
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ConnectionEstablished, rhs: Peariscope_ConnectionEstablished) -> Bool {
    if lhs.peerKey != rhs.peerKey {return false}
    if lhs.streamID != rhs.streamID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ConnectionFailed: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ConnectionFailed"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}connection_code\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.connectionCode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.connectionCode.isEmpty {
      try visitor.visitSingularStringField(value: self.connectionCode, fieldNumber: 1)
    }
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ConnectionFailed, rhs: Peariscope_ConnectionFailed) -> Bool {
    if lhs.connectionCode != rhs.connectionCode {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_Error: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Error"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != 0 {
      try visitor.visitSingularUInt32Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_Error, rhs: Peariscope_Error) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_StreamData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{1}channel\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.channel) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularUInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.channel != .video {
      try visitor.visitSingularEnumField(value: self.channel, fieldNumber: 2)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_StreamData, rhs: Peariscope_StreamData) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_InputEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".InputEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{1}key\0\u{3}mouse_move\0\u{3}mouse_button\0\u{1}scroll\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.timestampMs) }()
      case 2: try {
        var v: Peariscope_KeyEvent?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .key(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .key(v)
        }
      }()
      case 3: try {
        var v: Peariscope_MouseMoveEvent?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .mouseMove(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .mouseMove(v)
        }
      }()
      case 4: try {
        var v: Peariscope_MouseButtonEvent?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .mouseButton(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .mouseButton(v)
        }
      }()
      case 5: try {
        var v: Peariscope_ScrollEvent?
        var hadOneofValue = false
        if let current = self.event {
          hadOneofValue = true
          if case .scroll(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.event = .scroll(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.timestampMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.timestampMs, fieldNumber: 1)
    }
    switch self.event {
    case .key?: try {
      guard case .key(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .mouseMove?: try {
      guard case .mouseMove(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .mouseButton?: try {
      guard case .mouseButton(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .scroll?: try {
      guard case .scroll(let v)? = self.event else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_InputEvent, rhs: Peariscope_InputEvent) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.event != rhs.event {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_KeyEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}keycode\0\u{1}modifiers\0\u{1}pressed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.keycode) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.modifiers) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.keycode != 0 {
      try visitor.visitSingularUInt32Field(value: self.keycode, fieldNumber: 1)
    }
    if self.modifiers != 0 {
      try visitor.visitSingularUInt32Field(value: self.modifiers, fieldNumber: 2)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_KeyEvent, rhs: Peariscope_KeyEvent) -> Bool {
    if lhs.keycode != rhs.keycode {return false}
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_MouseMoveEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MouseMoveEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_MouseMoveEvent, rhs: Peariscope_MouseMoveEvent) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_MouseButtonEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MouseButtonEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}button\0\u{1}pressed\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.button) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.pressed) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.button != 0 {
      try visitor.visitSingularUInt32Field(value: self.button, fieldNumber: 1)
    }
    if self.pressed != false {
      try visitor.visitSingularBoolField(value: self.pressed, fieldNumber: 2)
    }
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 3)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_MouseButtonEvent, rhs: Peariscope_MouseButtonEvent) -> Bool {
    if lhs.button != rhs.button {return false}
    if lhs.pressed != rhs.pressed {return false}
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ScrollEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScrollEvent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}delta_x\0\u{3}delta_y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.deltaX) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.deltaY) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.deltaX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.deltaX, fieldNumber: 1)
    }
    if self.deltaY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.deltaY, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ScrollEvent, rhs: Peariscope_ScrollEvent) -> Bool {
    if lhs.deltaX != rhs.deltaX {return false}
    if lhs.deltaY != rhs.deltaY {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ControlMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControlMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}codec_negotiation\0\u{3}request_idr\0\u{3}quality_report\0\u{1}clipboard\0\u{3}frame_timestamp\0\u{3}peer_challenge\0\u{3}peer_challenge_response\0\u{3}display_list\0\u{3}switch_display\0\u{3}cursor_position\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Peariscope_CodecNegotiation?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .codecNegotiation(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .codecNegotiation(v)
        }
      }()
      case 2: try {
        var v: Peariscope_RequestIdr?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .requestIdr(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .requestIdr(v)
        }
      }()
      case 3: try {
        var v: Peariscope_QualityReport?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .qualityReport(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .qualityReport(v)
        }
      }()
      case 4: try {
        var v: Peariscope_ClipboardData?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .clipboard(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .clipboard(v)
        }
      }()
      case 5: try {
        var v: Peariscope_FrameTimestamp?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .frameTimestamp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .frameTimestamp(v)
        }
      }()
      case 6: try {
        var v: Peariscope_PeerChallenge?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .peerChallenge(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .peerChallenge(v)
        }
      }()
      case 7: try {
        var v: Peariscope_PeerChallengeResponse?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .peerChallengeResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .peerChallengeResponse(v)
        }
      }()
      case 8: try {
        var v: Peariscope_DisplayList?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .displayList(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .displayList(v)
        }
      }()
      case 9: try {
        var v: Peariscope_SwitchDisplay?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .switchDisplay(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .switchDisplay(v)
        }
      }()
      case 10: try {
        var v: Peariscope_CursorPosition?
        var hadOneofValue = false
        if let current = self.msg {
          hadOneofValue = true
          if case .cursorPosition(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.msg = .cursorPosition(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.msg {
    case .codecNegotiation?: try {
      guard case .codecNegotiation(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .requestIdr?: try {
      guard case .requestIdr(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .qualityReport?: try {
      guard case .qualityReport(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .clipboard?: try {
      guard case .clipboard(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .frameTimestamp?: try {
      guard case .frameTimestamp(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .peerChallenge?: try {
      guard case .peerChallenge(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .peerChallengeResponse?: try {
      guard case .peerChallengeResponse(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .displayList?: try {
      guard case .displayList(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .switchDisplay?: try {
      guard case .switchDisplay(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .cursorPosition?: try {
      guard case .cursorPosition(let v)? = self.msg else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ControlMessage, rhs: Peariscope_ControlMessage) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_CursorPosition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CursorPosition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}x\0\u{1}y\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.x) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.y) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.x.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.x, fieldNumber: 1)
    }
    if self.y.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.y, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_CursorPosition, rhs: Peariscope_CursorPosition) -> Bool {
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_PeerChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PeerChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pin\0\u{3}peer_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.peerKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pin.isEmpty {
      try visitor.visitSingularStringField(value: self.pin, fieldNumber: 1)
    }
    if !self.peerKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_PeerChallenge, rhs: Peariscope_PeerChallenge) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.peerKey != rhs.peerKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_PeerChallengeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PeerChallengeResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pin\0\u{1}accepted\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.pin) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pin.isEmpty {
      try visitor.visitSingularStringField(value: self.pin, fieldNumber: 1)
    }
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_PeerChallengeResponse, rhs: Peariscope_PeerChallengeResponse) -> Bool {
    if lhs.pin != rhs.pin {return false}
    if lhs.accepted != rhs.accepted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_DisplayList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayList"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}displays\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.displays) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displays.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.displays, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_DisplayList, rhs: Peariscope_DisplayList) -> Bool {
    if lhs.displays != rhs.displays {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_DisplayInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DisplayInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_id\0\u{1}width\0\u{1}height\0\u{1}name\0\u{3}is_active\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.displayID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isActive) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.displayID != 0 {
      try visitor.visitSingularUInt32Field(value: self.displayID, fieldNumber: 1)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 2)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 3)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 4)
    }
    if self.isActive != false {
      try visitor.visitSingularBoolField(value: self.isActive, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_DisplayInfo, rhs: Peariscope_DisplayInfo) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.name != rhs.name {return false}
    if lhs.isActive != rhs.isActive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_SwitchDisplay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwitchDisplay"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.displayID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.displayID != 0 {
      try visitor.visitSingularUInt32Field(value: self.displayID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_SwitchDisplay, rhs: Peariscope_SwitchDisplay) -> Bool {
    if lhs.displayID != rhs.displayID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_FrameTimestamp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FrameTimestamp"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}capture_time_ms\0\u{3}frame_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.captureTimeMs) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.frameID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.captureTimeMs != 0 {
      try visitor.visitSingularUInt64Field(value: self.captureTimeMs, fieldNumber: 1)
    }
    if self.frameID != 0 {
      try visitor.visitSingularUInt32Field(value: self.frameID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_FrameTimestamp, rhs: Peariscope_FrameTimestamp) -> Bool {
    if lhs.captureTimeMs != rhs.captureTimeMs {return false}
    if lhs.frameID != rhs.frameID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_CodecNegotiation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CodecNegotiation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supported_codecs\0\u{3}selected_codec\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedEnumField(value: &self.supportedCodecs) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.selectedCodec) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.supportedCodecs.isEmpty {
      try visitor.visitPackedEnumField(value: self.supportedCodecs, fieldNumber: 1)
    }
    if self.selectedCodec != .h264 {
      try visitor.visitSingularEnumField(value: self.selectedCodec, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_CodecNegotiation, rhs: Peariscope_CodecNegotiation) -> Bool {
    if lhs.supportedCodecs != rhs.supportedCodecs {return false}
    if lhs.selectedCodec != rhs.selectedCodec {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_RequestIdr: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestIdr"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_RequestIdr, rhs: Peariscope_RequestIdr) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_QualityReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".QualityReport"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}rtt_ms\0\u{3}packet_loss\0\u{3}bitrate_kbps\0\u{1}fps\0\u{3}screen_width\0\u{3}screen_height\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.rttMs) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.packetLoss) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.bitrateKbps) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.fps) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.screenWidth) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.screenHeight) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.rttMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.rttMs, fieldNumber: 1)
    }
    if self.packetLoss.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.packetLoss, fieldNumber: 2)
    }
    if self.bitrateKbps != 0 {
      try visitor.visitSingularUInt32Field(value: self.bitrateKbps, fieldNumber: 3)
    }
    if self.fps != 0 {
      try visitor.visitSingularUInt32Field(value: self.fps, fieldNumber: 4)
    }
    if self.screenWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.screenWidth, fieldNumber: 5)
    }
    if self.screenHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.screenHeight, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_QualityReport, rhs: Peariscope_QualityReport) -> Bool {
    if lhs.rttMs != rhs.rttMs {return false}
    if lhs.packetLoss != rhs.packetLoss {return false}
    if lhs.bitrateKbps != rhs.bitrateKbps {return false}
    if lhs.fps != rhs.fps {return false}
    if lhs.screenWidth != rhs.screenWidth {return false}
    if lhs.screenHeight != rhs.screenHeight {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_ClipboardData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClipboardData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_ClipboardData, rhs: Peariscope_ClipboardData) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_StatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StatusRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_StatusRequest, rhs: Peariscope_StatusRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_StatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StatusResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_hosting\0\u{3}is_connected\0\u{3}connected_peers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isHosting) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isConnected) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.connectedPeers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isHosting != false {
      try visitor.visitSingularBoolField(value: self.isHosting, fieldNumber: 1)
    }
    if self.isConnected != false {
      try visitor.visitSingularBoolField(value: self.isConnected, fieldNumber: 2)
    }
    if !self.connectedPeers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.connectedPeers, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_StatusResponse, rhs: Peariscope_StatusResponse) -> Bool {
    if lhs.isHosting != rhs.isHosting {return false}
    if lhs.isConnected != rhs.isConnected {return false}
    if lhs.connectedPeers != rhs.connectedPeers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Peariscope_PeerInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PeerInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}public_key\0\u{1}name\0\u{3}rtt_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.rttMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.publicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if self.rttMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.rttMs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Peariscope_PeerInfo, rhs: Peariscope_PeerInfo) -> Bool {
    if lhs.publicKey != rhs.publicKey {return false}
    if lhs.name != rhs.name {return false}
    if lhs.rttMs != rhs.rttMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
